# This is a basic workflow to help you get started with Actions

name: run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-11
    strategy:
      matrix: 
        image: [system-images;android-33;google_apis_playstore;x86_64]
        # tools: [cmdline-tools/latest, tools], 'tools' obsolete and issue annoying messages
        # see https://developer.android.com/studio/releases/sdk-tools
        tools: [cmdline-tools/latest]
        emulator: [emulator/emulator, tools/emulator]
        # gpu: [host, guest], 'host' takes forever 
        gpu: [guest, swiftshader_indirect]
        device: [Pixel_2_API_33]
  
    steps: 
      - name: Matrix
        env:
          TOOLS: ${{ matrix.tools }}
          IMAGE: ${{ matrix.image }}
          DEVICE: ${{ matrix.device }}
          EMULATOR: ${{ matrix.emulator }}
          GPU: ${{ matrix.gpu }}
        run: |
          echo "tools: $ANDROID_HOME/$TOOLS"
          echo "emulator: $EMULATOR"
          echo "image: $IMAGE"
          echo "DEVICE: $DEVICE"
          echo "-gpu: $GPU"
          
      - name: Cache images
        id: system-images
        uses: actions/cache@v3
        # the same ~40 secs + checks update as "Download image"
        if: ${{ false }}
        with:
          path:  /Users/runner/Library/Android/sdk/system-images
          key: system-images     
          
      - name: Cache emulator
        id: emulator
        uses: actions/cache@v3
        with:
          path:  /Users/runner/Library/Android/sdk/emulator
          key: system-emulator
        
      - name: sdkmanager --list
        env:
          TOOLS: ${{ matrix.tools }}
        run: |
          set -x
          $ANDROID_HOME/$TOOLS/bin/sdkmanager --list 
          
      - name: Download image
        env:
          TOOLS: ${{ matrix.tools }}
          IMAGE: ${{ matrix.image }}
        run: |
          set -x
          echo "y" | $ANDROID_HOME/$TOOLS/bin/sdkmanager --install $IMAGE
          
      - name: Apply licenses
        env:
          TOOLS: ${{ matrix.tools }}
        run: |
          set -x
          echo "y" | $ANDROID_HOME/$TOOLS/bin/sdkmanager --licenses
          
      - name: Create Android emulator
        env:
          TOOLS: ${{ matrix.tools }}
          IMAGE: ${{ matrix.image }}
          DEVICE: ${{ matrix.device }}
          EMULATOR: ${{ matrix.emulator }}
        run: |
          echo "no" | $ANDROID_HOME/$TOOLS/bin/avdmanager create avd -n $DEVICE -d pixel --package $IMAGE --force
          $ANDROID_HOME/$EMULATOR -list-avds
          
      - name: update emulator
        env:
          EMULATOR: ${{ matrix.emulator }}
          TOOLS: ${{ matrix.tools }}
        run: |
          echo "current version"
          $ANDROID_HOME/$EMULATOR -version
          echo "y" | $ANDROID_HOME/$TOOLS/bin/sdkmanager --install emulator
          echo "updated version"
          $ANDROID_HOME/$EMULATOR -version
          
      - name: Set up virtualization
        env:
          EMULATOR: ${{ matrix.emulator }}
        run: |
          echo "$ANDROID_HOME/$EMULATOR-check accel"
          $ANDROID_HOME/$EMULATOR-check accel || true
          echo "$ANDROID_HOME/$EMULATOR-check cpu-info"
          $ANDROID_HOME/$EMULATOR-check cpu-info || true
          # non nessary if HAXM is not installed
          sysctl kern.hv_support
          echo 'HVF = on' >> ~/.android/advancedFeatures.ini
          cat ~/.android/advancedFeatures.ini
          
      - name: Start Android emulator
        env:
          TOOLS: ${{ matrix.tools }}
          IMAGE: ${{ matrix.image }}
          DEVICE: ${{ matrix.device }}
          EMULATOR: ${{ matrix.emulator }}
          GPU: ${{ matrix.gpu }}
        run: |
          echo "Starting emulator"
          nohup $ANDROID_HOME/$EMULATOR -gpu $GPU -avd $DEVICE -prop -perf-stat -no-snapshot -no-audio -no-boot-anim -camera-back none -camera-front none -cores 2 -qemu -m 2048 2>&1 &
          echo "Waiting for boot to complete..."
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do echo "wait..."; sleep 1; done; input keyevent 82'
          echo "Emulator has finished booting"
          $ANDROID_HOME/platform-tools/adb devices
          
      - name: Make screenshots
        run: |
          sleep 45
          screencapture screenshot.jpg
          $ANDROID_HOME/platform-tools/adb exec-out screencap -p > emulator.png
          
      - uses: actions/upload-artifact@v3
        with:
          name: screenshot.jpg
          path: screenshot.jpg
          
      - uses: actions/upload-artifact@v3
        with:
          name: emulator.png
          path: emulator.png
